---
AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to deploy IAM resources and Log Groups. Includes Instance Profile, Role, Log Groups.
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: Choose either dev or prod
  ProjectName:
    Type: String
    Description: Represents the project name
  Owner:
    Type: String
    Description: Represents the owner of the project
  ManagedBy:
    Type: String
    Description: Represents the IAC used
  APPEC2Role:
    Type: String
    Description: |
      Represents the name associated to an IAM Role attached to the
      EC2 instance
    AllowedPattern: ^[\w+=,.@-]+$
  CloudWatchPolicyName:
    Type: String
    Description: Represents the name of the cloudwatch policy
  CloudWatchAgentPolicyName:
    Type: String
    Description: Represents the name of the cloudwatch agent policy
  S3BucketPolicyName:
    Type: String
    Description: Represents the name of the s3 bucket policy
  EC2MetadataPolicyName:
    Type: String
    Description: Represents the name of the ec2 metadata policy
  CloudFormationPolicyName:
    Type: String
    Description: Represents the name of the cloudformation policy
  DynamoDBPolicyName:
    Type: String
    Description: Represents the name of the dynamoDB table that holds the drift results
  PurposeOfCloudInitLogGrp:
    Type: String
    Description: |
      Represents the purpose of the log group for cloud init level logs
    AllowedPattern: ^[A-Za-z0-9]+$
  ComponentOfCloudInitLogGrp:
    Type: String
    Description: Represents the component of the log group for system level logs
    AllowedPattern: ^[-A-Za-z0-9]+$
  NameOfCloudInitLogGrp:
    Type: String
    Description: Represents the name of the log group for system level logs
    AllowedPattern: ^[-A-Za-z0-9]+$
  PurposeOfSystemLogGrp:
    Type: String
    Description: Represents the purpose of the log group for system level logs
    AllowedPattern: ^[A-Za-z0-9]+$
  ComponentOfSystemLogGrp:
    Type: String
    Description: Represents the component of the log group for system level logs
    AllowedPattern: ^[-A-Za-z0-9]+$
  NameOfSystemLogGrp:
    Type: String
    Description: Represents the name of the log group for system level logs
    AllowedPattern: ^[-A-Za-z0-9]+$
  PurposeOfApplicationLogGrp:
    Type: String
    Description: Represents the purpose of the log group for application level logs
    AllowedPattern: ^[A-Za-z0-9]+$
  ComponentOfApplicationLogGrp:
    Type: String
    Description: Represents the component of the log group for application level logs
    AllowedPattern: ^[-A-Za-z0-9]+$
  NameOfApplicationLogGrp:
    Type: String
    Description: Represents the name of the log group for application level logs
    AllowedPattern: ^[-A-Za-z0-9]+$
Resources:
  CloudInitLogGroup:
    Type: AWS::Logs::LogGroup
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_158
            comment: "Skipping KMS encryption for the log group temporarily to avoid costs."
    Properties:
      LogGroupClass: STANDARD
      LogGroupName: !Sub "${Environment}/${PurposeOfCloudInitLogGrp}/${ComponentOfCloudInitLogGrp}/${NameOfCloudInitLogGrp}"
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-cloud-init-log-grp"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Owner
          Value: !Ref Owner
  SystemLogGroup:
    Type: AWS::Logs::LogGroup
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_158
            comment: "Skipping KMS encryption for the log group temporarily to avoid costs."
    Properties:
      LogGroupClass: STANDARD
      LogGroupName: !Sub "${Environment}/${PurposeOfSystemLogGrp}/${ComponentOfSystemLogGrp}/${NameOfSystemLogGrp}"
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-system-log-grp"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Owner
          Value: !Ref Owner
  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_158
            comment: "Skipping KMS encryption for the log group temporarily to avoid costs."
    Properties:
      LogGroupClass: STANDARD
      LogGroupName: !Sub "${Environment}/${PurposeOfApplicationLogGrp}/${ComponentOfApplicationLogGrp}/${NameOfApplicationLogGrp}"
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-application-log-grp"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Owner
          Value: !Ref Owner
  EC2IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: |
        Provides access to read the S3 bucket, SSM access forinstance
        access, write logs to cloudwatch
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !GetAtt CloudWatchPolicy.PolicyArn
        - !GetAtt CloudWatchAgentPolicy.PolicyArn
        - !GetAtt S3BucketPolicy.PolicyArn
        - !GetAtt EC2MetadataPolicy.PolicyArn
        - !GetAtt CloudFormationPolicy.PolicyArn
        - !GetAtt DynamoDBPolicy.PolicyArn
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      RoleName: !Sub '${APPEC2Role}-${AWS::StackName}'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Owner
          Value: !Ref Owner
  CloudWatchPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Represents the permission for accessing the cloudwatch logs
      ManagedPolicyName: !Ref CloudWatchPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
            Resource:
              - !Sub "${CloudInitLogGroup.Arn}"
              - !Sub "${SystemLogGroup.Arn}"
              - !Sub "${ApplicationLogGroup.Arn}"
          
          - Effect: Allow
            Action:
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
              - 'logs:DescribeLogStreams'
            Resource:
              - !Sub "${CloudInitLogGroup.Arn}:*"
              - !Sub "${SystemLogGroup.Arn}:*"
              - !Sub "${ApplicationLogGroup.Arn}:*"
  CloudWatchAgentPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Represents the permission for cloudwatch agent
      ManagedPolicyName: !Ref CloudWatchAgentPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'cloudwatch:PutMetricData'
            Resource: '*'
  S3BucketPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Represents the permission for s3 bucket
      ManagedPolicyName: !Ref S3BucketPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 's3:ListBucket'
            Resource: !Sub 'arn:aws:s3:::${Environment}-app-artifact-bkt'
          - Effect: Allow
            Action:
              - 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${Environment}-app-artifact-bkt/*'
  EC2MetadataPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Represents the permission for ec2 metadata
      ManagedPolicyName: !Ref EC2MetadataPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ec2:DescribeTags"
              - "autoscaling:DescribeAutoScalingInstances"
            Resource: '*'
  CloudFormationPolicy:
    Type: AWS::IAM::ManagedPolicy
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_111
            comment: "Global skip for this stack to accommodate wildcard constraints."
    Properties:
      Description: Represents the permission for cloudformation
      ManagedPolicyName: !Ref CloudFormationPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'cloudformation:DescribeStackResource'
              - 'cloudformation:DescribeStackResources'
              - 'cloudformation:DescribeStacks'
              - 'cloudformation:SignalResource'
              - 'cloudformation:ListStacks'
              - 'cloudformation:DetectStackDrift'
              - 'cloudformation:DescribeStackDriftDetectionStatus'
              - 'cloudformation:DescribeStackResourceDrifts'
            Resource: '*'
  DynamoDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Represents the permission for dynamoDB table that holds drift results
      ManagedPolicyName: !Ref DynamoDBPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:Scan
            Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Environment}-infrastructure-scan-results"
  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2IAMRole
      InstanceProfileName: !Sub '${APPEC2Role}-${AWS::StackName}'
Outputs:
  EC2Role:
    Value: !Ref EC2IAMRole
    Description: Represents the IAM Role name
    Export:
      Name: !Sub "${Environment}-security-ec2-role"
  EC2RoleARN:
    Value: !GetAtt EC2IAMRole.Arn
    Description: Represents the IAM Role ARN
    Export:
      Name: !Sub "${Environment}-security-ec2-role-arn"
  IProfileName:
    Value: !GetAtt AppInstanceProfile.Arn
    Description: Represents the IAM Instance profile name
    Export:
      Name: !Sub "${Environment}-security-instance-profile-arn"