AWSTemplateFormatVersion: "2010-09-09"

Description: Stack to deploy the platform infrastructure. Specifically the DynamoDB table. Includes ssm parameter representing the DynamoDB table.

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: Choose either dev or prod
  ProjectName:
    Type: String
    Description: Represents the project name
  Owner:
    Type: String
    Description: Represents the owner of the project
  ManagedBy:
    Type: String
    Description: Represents the IAC used
  DriftTableName:
    Type: String
    Description: Represents the table name that contains drift results
Resources:
  DriftResultsTable:
    Type: AWS::DynamoDB::Table
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_119
            comment: "Skipping KMS encryption for the CMK for tables"
    Properties:
      TableName: !Ref DriftTableName
      BillingMode: PAY_PER_REQUEST
      # Keys and their type
      AttributeDefinitions:
        - AttributeName: AccountId
          AttributeType: S
        - AttributeName: ScanTime
          AttributeType: S
      # Defining roles for the attributes, here HASH -> Primary Key
      KeySchema:
        - AttributeName: AccountId
          KeyType: HASH
        - AttributeName: ScanTime
          KeyType: RANGE

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
  DriftTableParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/portfolio/${Environment}/drift-table"
      Type: String
      Value: !Ref DriftResultsTable
      Description: Represents the name of the table which holds drift results
      Tags:
        Environment: !Ref Environment
        Project: !Ref ProjectName
        ManagedBy: !Ref ManagedBy
        Owner: !Ref Owner
Outputs:
  DriftResultsTableARN:
    Description: Represents the ARN of the drift results table
    Value: !GetAtt DriftResultsTable.Arn
    Export:
      Name: DriftResultsTableARN
  DriftTableParameter:
    Value: !Ref DriftTableParameter
    Description: Represents the name of the SSM Parameter for dynamodb table containing drift results