name: Application Deployment Pipeline

on:
  push:
    paths:
      - 'aws-infra-governance-assistant/**'
    branches:
      - dev
      - prod

  workflow_dispatch:

concurrency:
  group: platform-deploy-${{ github.ref_name }}
  cancel-in-progress: false
  queue: max

env:
  AWS_REGION: us-east-1
  ENVIRONMENT: ${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev'}}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      sha: ${{ steps.vars.outputs.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Retrieve SHA value
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Construct build Folder
        run: |
          rm -rf build
          mkdir -p build

      - name: Build App Artifact
        run: |
          cp -r aws-infra-governance-assistant/app build/
          cp aws-infra-governance-assistant/requirements.txt build/

      - name: Create Zip
        run: |
          cd build
          zip -r app.zip .
          mv app.zip ../app.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: app-zip
          path: app.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/dev' && secrets.DEV_APP_DEPLOYMENT_ROLE_ARN || secrets.PROD_APP_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download Build Artifact
        uses: actions/download-artifact@v8
        with:
          name: app-zip

      - name: Get Version
        run: echo "SHA=${{ needs.build.outputs.sha }}" >> "${GITHUB_ENV}"

      - name: Fetch Bucket name from SSM
        run: |
          ARTIFACT_BUCKET=$(aws ssm get-parameter \
            --name "/portfolio/${{ env.ENVIRONMENT }}/artifact-bucket" \
            --query "Parameter.Value" \
            --region ${{ env.AWS_REGION }} \
            --output text)

          if [ -z "$ARTIFACT_BUCKET" ]; then
            echo "⚠️ Infra not ready - skipping deployment safely"
            exit 0
          else
            echo "Fetched Bucket: ${ARTIFACT_BUCKET}"
          fi

          echo "ARTIFACT_BUCKET=${ARTIFACT_BUCKET}" >> "${GITHUB_ENV}"

      - name: Upload Artifact to S3
        run: |
          aws s3 cp app.zip \
            s3://${ARTIFACT_BUCKET}/app/releases/${SHA}.zip

      - name: Update Version Files (SSM-backed S3)
        run: |
          mkdir -p /tmp/version

          if aws s3api head-object --bucket "${ARTIFACT_BUCKET}" --key "app/versions/current.txt" >/dev/null 2>&1; then
            echo "Current version found. Backing it up to previous.txt..."
            aws s3 cp s3://${ARTIFACT_BUCKET}/app/versions/current.txt s3://${ARTIFACT_BUCKET}/app/versions/previous.txt
          else
            echo "First deployment! No current.txt file found. Skipping backup."
          fi

          echo $SHA > /tmp/version/current.txt
          aws s3 cp /tmp/version/current.txt s3://${ARTIFACT_BUCKET}/app/versions/current.txt

      - name: Fetch ASG name from SSM
        run: |
          ASG_NAME=$(aws ssm get-parameter \
            --name "/portfolio/${{ env.ENVIRONMENT }}/asg-name" \
            --query "Parameter.Value" \
            --output text 2>/dev/null || true)

          if [ -z "${ASG_NAME}" ]; then
            echo "⚠️ Bootstrap detected: ASG not found in SSM."
            echo "✔ Artifact uploaded and version updated."
            echo "✔ Version updated"
            echo "⏭ Skipping instance refresh"
            exit 0
          fi

          echo "ASG_NAME=${ASG_NAME}" >> "${GITHUB_ENV}"

      - name: Trigger Instance Refresh (if ASG exists)
        run: |

          echo "🚀 Triggering Instance Refresh for ASG: ${ASG_NAME}"

          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name "${ASG_NAME}" \
            --preferences '{
              "MinHealthyPercentage": 50,
              "MaxHealthyPercentage": 100,
              "InstanceWarmup": 120,
              "SkipMatching": false
            }' \
            --query 'InstanceRefreshId' \
            --output text)

          echo "REFRESH_ID=$REFRESH_ID" >> $GITHUB_ENV

      - name: Wait for Instance Refresh
        run: |
          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name "${ASG_NAME}" \
              --instance-refresh-ids "${REFRESH_ID}" \
              --query "InstanceRefreshes[0].Status" \
              --output text 2>/dev/null)

            if [[ -z "$STATUS" || "$STATUS" == "None" || "$STATUS" == "null" ]]; then
              echo "Waiting for instance refresh to become visible..."
              sleep 5
              continue
            fi
            
            echo "Status: $STATUS"

            if [ "$STATUS" == "Successful" ]; then
              exit 0
            fi

            if [ "$STATUS" == "Failed" ] || [ "$STATUS" == "Cancelled" ]; then
              exit 1
            fi

            sleep 20
          done
