name: IAC Validation Pipeline

on:
  pull_request:
    branches:
      - dev
      - prod

jobs:

  changes:
    runs-on: ubuntu-latest

    outputs:

      platform: ${{ steps.filter.outputs.platform }}
      application: ${{ steps.filter.outputs.application }}
      lt: ${{ steps.filter.outputs.lt }}
      network: ${{ steps.filter.outputs.network }}
      security: ${{ steps.filter.outputs.security }}
      storage: ${{ steps.filter.outputs.storage }}
      infrastructure: ${{ steps.filter.outputs.infrastructure }}

    steps:
      - name: Checkout Code
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            platform:
              - 'infra/platform/**'
            application:
              - 'infra/application/**'
            lt:
              - 'infra/launch-template/**'
            network:
              - 'infra/network/**'
            security:
              - 'infra/security/**'
            storage:
              - 'infra/storage/**'
            infrastructure:
              - 'infra/platform/**'
              - 'infra/application/**'
              - 'infra/launch-template/**'
              - 'infra/network/**'
              - 'infra/security/**'
              - 'infra/storage/**'

  setup:
    runs-on: ubuntu-latest
    outputs:
      env_tier: ${{ steps.vars.outputs.env_tier }}
    steps:
      - name: Determine Environment Tier
        id: vars
        run: |
          if [ "${{ github.base_ref }}" == "prod" ]; then
            echo "env_tier=PROD" >> $GITHUB_OUTPUT
          else
            echo "env_tier=DEV" >> $GITHUB_OUTPUT
          fi

  validate-platform-infra:
    needs: [changes, setup]
    if: ${{ needs.changes.outputs.platform == 'true'}}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: 'us-east-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets[format('{0}_VALIDATION_ROLE_ARN', needs.setup.outputs.env_tier )] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set stack
        id: stacks
        run: echo "STACK=platform" >> $GITHUB_ENV

      - name: Validate and deploy ${STACK}-stack
        run: |
          set -e

          echo "==== Processing stack: $STACK-stack ===="

          TEMPLATE_FILE="infra/$STACK/$STACK-stack.yaml"

          echo "-> Running yamllint..."
          yamllint $TEMPLATE_FILE

          echo "-> Running cfn-lint..."
          cfn-lint $TEMPLATE_FILE

          echo "-> Running cloudformation validate..."
          aws cloudformation validate-template \
              --template-body file://$TEMPLATE_FILE

  validate-application-infra:
    needs: [changes, setup]
    if: ${{ needs.changes.outputs.application == 'true' }}
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets[format('{0}_VALIDATION_ROLE_ARN', needs.setup.outputs.env_tier )] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set stack
        id: stacks
        run: echo "STACK=application" >> $GITHUB_ENV

      - name: Validate and deploy ${STACK}-stack
        run: |
          set -e

          echo "==== Processing stack: $STACK-stack ===="

          TEMPLATE_FILE="infra/$STACK/$STACK-stack.yaml"

          echo "-> Running yamllint..."
          yamllint $TEMPLATE_FILE

          echo "-> Running cfn-lint..."
          cfn-lint $TEMPLATE_FILE

          echo "-> Running cloudformation validate..."
          aws cloudformation validate-template \
              --template-body file://$TEMPLATE_FILE

  validate-lt:
    needs: [changes, setup]
    if: ${{ needs.changes.outputs.lt == 'true' }}
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read

    env:
      AWS_REGION: 'us-east-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets[format('{0}_VALIDATION_ROLE_ARN', needs.setup.outputs.env_tier )] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set stack
        id: stacks
        run: echo "STACK=launch-template" >> $GITHUB_ENV

      - name: Validate and deploy ${STACK}-stack
        run: |
          set -e

          echo "==== Processing stack: $STACK-stack ===="

          TEMPLATE_FILE="infra/$STACK/$STACK-stack.yaml"

          echo "-> Running yamllint..."
          yamllint $TEMPLATE_FILE

          echo "-> Running cfn-lint..."
          cfn-lint $TEMPLATE_FILE

          echo "-> Running cloudformation validate..."
          aws cloudformation validate-template \
              --template-body file://$TEMPLATE_FILE

  validate-network-infra:
    needs: [changes, setup]
    if: ${{ needs.changes.outputs.network == 'true' }}
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read

    env:
      AWS_REGION: 'us-east-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets[format('{0}_VALIDATION_ROLE_ARN', needs.setup.outputs.env_tier )] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set stack
        id: stacks
        run: echo "STACK=network" >> $GITHUB_ENV

      - name: Validate and deploy ${STACK}-stack
        run: |
          set -e

          echo "==== Processing stack: $STACK-stack ===="

          TEMPLATE_FILE="infra/$STACK/$STACK-stack.yaml"

          echo "-> Running yamllint..."
          yamllint $TEMPLATE_FILE

          echo "-> Running cfn-lint..."
          cfn-lint $TEMPLATE_FILE

          echo "-> Running cloudformation validate..."
          aws cloudformation validate-template \
              --template-body file://$TEMPLATE_FILE
  
  validate-security-infra:
    needs: [changes, setup]
    if: ${{ needs.changes.outputs.security == 'true' }}
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read

    env:
      AWS_REGION: 'us-east-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets[format('{0}_VALIDATION_ROLE_ARN', needs.setup.outputs.env_tier )] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set stack
        id: stacks
        run: echo "STACK=security" >> $GITHUB_ENV

      - name: Validate and deploy ${STACK}-stack
        run: |
          set -e

          echo "==== Processing stack: $STACK-stack ===="

          TEMPLATE_FILE="infra/$STACK/$STACK-stack.yaml"

          echo "-> Running yamllint..."
          yamllint $TEMPLATE_FILE

          echo "-> Running cfn-lint..."
          cfn-lint $TEMPLATE_FILE

          echo "-> Running cloudformation validate..."
          aws cloudformation validate-template \
              --template-body file://$TEMPLATE_FILE
  
  validate-storage-infra:
    needs: [changes, setup]
    if: ${{ needs.changes.outputs.storage == 'true' }}
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read

    env:
      AWS_REGION: 'us-east-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets[format('{0}_VALIDATION_ROLE_ARN', needs.setup.outputs.env_tier )] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set stack
        id: stacks
        run: echo "STACK=storage" >> $GITHUB_ENV

      - name: Validate and deploy ${STACK}-stack
        run: |
          set -e

          echo "==== Processing stack: $STACK-stack ===="

          TEMPLATE_FILE="infra/$STACK/$STACK-stack.yaml"

          echo "-> Running yamllint..."
          yamllint $TEMPLATE_FILE

          echo "-> Running cfn-lint..."
          cfn-lint $TEMPLATE_FILE

          echo "-> Running cloudformation validate..."
          aws cloudformation validate-template \
              --template-body file://$TEMPLATE_FILE

  checkov-scan:
    needs: changes
    if: ${{ needs.changes.outputs.infrastructure == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Checkov Scan
        run: |
          checkov \
            -d ./infra/application \
            -d ./infra/launch-template \
            -d ./infra/network \
            -d ./infra/platform \
            -d ./infra/security \
            -d ./infra/storage \
            --framework cloudformation \
            --external-checks-dir ./security/checkov/organization_policies \
            -o cli \
            -o json \
            --output-file-path checkov-report.json

      - name: Debug workspace
        if: always()
        run: |
          pwd
          ls -R

      - name: Upload Checkov Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: ./checkov-report.json

  validation-status:
    needs:
      - changes
      - validate-platform-infra
      - validate-application-infra
      - validate-lt
      - validate-network-infra
      - validate-security-infra
      - validate-storage-infra
      - checkov-scan

    if: ${{ always() }}

    runs-on: ubuntu-latest

    steps:
      - name: Validate infrastructure checks
        shell: bash
        run: |
          failed=false

          if [[ "${{ needs.changes.outputs.platform }}" == "true" && "${{ needs.validate-platform-infra.result }}" != "success" ]]; then
            echo "❌ Platform validation failed."
            failed=true
          fi

          if [[ "${{ needs.changes.outputs.application }}" == "true" && "${{ needs.validate-application-infra.result }}" != "success" ]]; then
            echo "❌ Application validation failed."
            failed=true
          fi

          if [[ "${{ needs.changes.outputs.lt }}" == "true" && "${{ needs.validate-lt.result }}" != "success" ]]; then
            echo "❌ Launch Template validation failed."
            failed=true
          fi

          if [[ "${{ needs.changes.outputs.network }}" == "true" && "${{ needs.validate-network-infra.result }}" != "success" ]]; then
            echo "❌ Network validation failed."
            failed=true
          fi

          if [[ "${{ needs.changes.outputs.security }}" == "true" && "${{ needs.validate-security-infra.result }}" != "success" ]]; then
            echo "❌ Security validation failed."
            failed=true
          fi

          if [[ "${{ needs.changes.outputs.storage }}" == "true" && "${{ needs.validate-storage-infra.result }}" != "success" ]]; then
            echo "❌ Storage validation failed."
            failed=true
          fi

          if [[ "${{ needs.changes.outputs.infrastructure }}" == "true" && "${{ needs.checkov-scan.result }}" != "success" ]]; then
            echo "❌ Checkov validation failed."
            failed=true
          fi

          if [[ "$failed" == "true" ]]; then
            echo "❌ Infrastructure validation failed."
            exit 1
          fi

          echo "✅ All applicable infrastructure validation checks passed."
          exit 0